ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ org.example.project.ApplicationKt.module ]
    }
}

storage {
    driverClassName = "org.h2.Driver"
    jdbcURL = "jdbc:h2:file:./build/db"
    jdbcURL = ${?JDBC_URL}
}

jwt {
    secret = "secret"
    secret = ${?JWT_SECRET}
    realm = "Access to 'TaxiApp'"
    accessTokenExpirationHours = 1
    refreshTokenExpirationDays = 30
    userIdClaimName = "userId"
}

google {
    clientIds = ${GOOGLE_CLIENT_IDS}
}
